# Site settings
title:              Something New Every Day
email:              johnp@bravelocation.com
twitter_username:   yeltzland
github_username:    bravelocation
url:                http://somethingneweveryday.bravelocation.com
baseurl:            ''
paginate:           10

# Build settings
markdown: kramdown

# Gems
gems: ['jekyll-paginate', 'jekyll-feed', 'jekyll-sitemap']

feed:
  path: rss.xml

# About/contact
author:
  name:              John Pollard
  url:               https://bravelocation.com/about
  email:             johnp@bravelocation.com
  twitter:           yeltzland
