safe:     false
port:     4000
url:      http://localhost:4000
paginate: 10
root_uri: http://somethingnew365.com

source:      .
destination: ./_site

# Build settings
markdown: kramdown

# Gems
gems: ['jekyll-paginate']